from typing import Any

from app.schemas import AnalysisOutput
from app.services.llm_clients import call_ollama, call_openai


POSITIVE_WORDS = {"good", "great", "awesome", "nice", "sahi", "mast", "love", "clean", "better", "happy"}
NEGATIVE_WORDS = {"bad", "poor", "kharab", "bekaar", "worst", "hate", "slow", "dirty", "issue", "problem"}
TOPIC_KEYWORDS = {
    "roads": {"road", "traffic", "street", "jam"},
    "safety": {"safe", "unsafe", "police", "crime"},
    "food": {"food", "chai", "restaurant", "snacks"},
    "market": {"market", "shop", "mall", "bazaar"},
    "services": {"hospital", "school", "water", "electricity", "wifi"},
    "events": {"festival", "event", "concert", "match"},
}


def _rule_based_topics(text: str) -> list[str]:
    lowered = text.lower()
    topics = [topic for topic, keywords in TOPIC_KEYWORDS.items() if any(keyword in lowered for keyword in keywords)]
    return topics[:3] or ["general"]


def _rule_based_sentiment(text: str) -> dict[str, Any]:
    tokens = set(text.lower().split())
    pos_hits = len(tokens & POSITIVE_WORDS)
    neg_hits = len(tokens & NEGATIVE_WORDS)
    topics = _rule_based_topics(text)

    if pos_hits and neg_hits:
        label = "mixed"
        score = 0.6
        emotion = "conflicted"
    elif pos_hits > neg_hits:
        label = "positive"
        score = min(0.95, 0.55 + pos_hits * 0.1)
        emotion = "satisfied"
    elif neg_hits > pos_hits:
        label = "negative"
        score = min(0.95, 0.55 + neg_hits * 0.1)
        emotion = "frustrated"
    else:
        label = "neutral"
        score = 0.5
        emotion = "neutral"

    return {
        "sentiment_label": label,
        "sentiment_score": round(score, 2),
        "dominant_topics": topics,
        "emotion": emotion,
        "reasoning": "Generated by offline lexical baseline for code-mixed text.",
    }


def _normalize_llm_output(payload: dict[str, Any], latency_ms: float) -> AnalysisOutput:
    label = str(payload.get("sentiment_label", "neutral")).lower()
    if label not in {"positive", "negative", "neutral", "mixed"}:
        label = "neutral"

    score = min(1.0, max(0.0, float(payload.get("sentiment_score", 0.5))))
    topics = payload.get("dominant_topics", [])
    if isinstance(topics, str):
        topics = [topic.strip() for topic in topics.split(",") if topic.strip()]
    if not isinstance(topics, list):
        topics = ["general"]

    return AnalysisOutput(
        sentiment_label=label,
        sentiment_score=round(score, 3),
        dominant_topics=topics[:5] or ["general"],
        emotion=str(payload.get("emotion", "neutral")),
        reasoning=str(payload.get("reasoning", ""))[:400],
        latency_ms=latency_ms,
    )


def analyze_text(text: str, provider: str) -> AnalysisOutput:
    provider = provider.lower()

    if provider == "rule_based":
        return _normalize_llm_output(_rule_based_sentiment(text), latency_ms=0.0)
    if provider == "openai":
        payload, latency_ms = call_openai(text)
        return _normalize_llm_output(payload, latency_ms)
    if provider == "ollama":
        payload, latency_ms = call_ollama(text)
        return _normalize_llm_output(payload, latency_ms)

    raise ValueError(f"Unsupported provider: {provider}")
